### ISSUE TITLE
Use latest icondata dependency?

### ISSUE THREAD

**Issue by adrianncovaci** [carloskiki/leptos-icons#29]
I recently executed cargo update and noticed that leptos-icons no longer compiles due to modifications in the [icondata](https://github.com/Carlosted/icondata) dependency. Specifically, utilities like the icon! macro are malfunctioning since their imports have been deleted. There are also new cargo features and others have been removed. Is there ongoing work to address this?

**Comment by carloskiki** [comment]
The `Icon!` macro was removed in version 0.1.0.

Icon features changed because the icon libraries of `icondata` were updated. In the future, it is planned for `leptos_icons` to only export the `Icon` component and let users bring in their own version of `icondata` (or perhaps another icon library). This would make `leptos_icons` more stable as right now breaking changes occur every time a icon library is updated.

Does that answer your question?
