### ISSUE TITLE
Include `x` and `y` attributes

### ISSUE THREAD

**Issue by bicarlsen** [carloskiki/leptos-icons#49]
Because the icons render in an `svg` tag, they can also be included in an outer `svg` tag, so exposing the `x` and `y` attributes would be useful.
e.g. 
```rust
use leptos_icons::*

#[component]
fn Canvas() -> impl IntoView {
  (y_pos, set_y_pos) = create_signal(0);
  // ...
  view! {
    <svg viewBox="0 0 100 100">
      <Icon icon=icondata::ChCross x="10" y=y_pos/>
    </svg>
  }
}
```

**Comment by carloskiki** [comment]
I believe you can [achieve this behaviour with CSS as well](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y#svg). When leptos 0.7 will be out, you will be able to apply this attribute without any support on our side with [enhanced attribute spreading](https://github.com/leptos-rs/leptos/releases/tag/0.7.0-alpha).

Because of the above reasons I do not believe it is a good idea to support your specific use case. Hence, I will close the issue, but feel free to re-open it if there are things I have not taken into consideration.
