### ISSUE TITLE
Maybe use something like https://iconify.design as icon source

### ISSUE THREAD

**Issue by freopen** [carloskiki/leptos-icons#8]
Maybe it will be easier to uniformly integrate multiple icon sets by using some icon set aggregator? I know that Iconify has a repository with all the icons as json files: https://github.com/iconify/icon-sets/tree/master/json.

**Comment by carloskiki** [comment]
This is surely something to consider.

I don't like the fact that a user has to be online to use the iconify API. The other way to do this would be to download the iconify icons. This would work, but we are already downloading every icon package, and I would prefer that only required icon libraries be downloaded to reduce the crate size because a crate can be a maximum of 10MB in size.

This is why I personally prefer the more fine-grain approach.

Do you see any advantages to using iconify?

**Comment by freopen** [comment]
I got the impression that it's nontrivial amount of work to add a new icon
set to the library in a unified way and most of that work is already done
by projects like Iconify, so I proposed it.

I don't think that online approach will work. For offline, I propose having
each image set in a separate crate. The main crate will conditionally
depend on feature-enabled image sets only. This approach is scalable to any
number of sets. It also means the user won't download image sets that are
feature-disabled.

Another idea to reduce crate size is that image set crate will only contain
a json file and a build script that generates classes from it. The build
script should be a single call to yet another crate so the builder code is
compiled once even when multiple image sets are enabled.
